### ISSUE TITLE
[Enhancement]: IMPROVE THE LOGIN AND SIGNUP & ADDED ENVIRONMENT VARIABLE

### ISSUE THREAD

**Issue by priyanshu1044** [shailifadadu/LinkShrink#2]
- Implement Environment Variables for Database Credentials and Jwt Secret Keys.
- Update the Codebase to Use Environment Variables for Db and Jwt.
- Modify the .gitignore File to Exclude Sensitive and Unnecessary Files.
- Enhance the Ui/ux of the Login and Signup Pages.
- Add Form Validation to the Login and Signup Pages.
- Add a Home Button to the Navigation Bar.

**Comment by shailifadadu** [comment]
@priyanshu1044 Thank you for contributing to LinkShrink. I have reviewed and merged your PR. Great work!!
